name: Enforce-Approvals/build

on:
  pull_request_review:
    types:
      - submitted

jobs:
  enforce-approvals:
    runs-on: ubuntu-latest
    name: Enforce-Approvals/build
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Enforce Approvals
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.SBANI_SECRETE }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const target_branch = context.payload.pull_request.base.ref;
            const pull_number = context.payload.pull_request.number;
            const team_slug = "tech-reviewers"; // Replace with your team's slug
            const org = "sbani-test-org";
            if (target_branch !== 'dev') {
              core.info(`Skipping PR #${pull_number} because it is not targeting 'dev' branch.`);
              return;
            }
            // Get list of approvals
            const reviews = await github.rest.pulls.listReviews({
              owner,
              repo,
              pull_number,
            });

            const approvals = reviews.data.filter(review => review.state === "APPROVED");

            if (approvals.length === 0) {
              core.setFailed("No approvals found.");
              return;
            }

            // Fetch all members of the tech-reviewers team
            const teamMembers = await github.rest.teams.listMembersInOrg({
              org,
              team_slug,
            });
            console.log(teamMembers)
            const teamMemberLogins = teamMembers.data.map(member => member.login);

            // Check if any approver is a member of the tech-reviewers team
            const validApproval = approvals.some(review =>
              teamMemberLogins.includes(review.user.login)
            );

            if (!validApproval) {
              core.setFailed("Pull request must be approved by at least one tech-reviewers team member.");
            } else {
              core.info("PR is approved by a tech-reviewers member.");
            }

